-- Carnet d'humeurs d'Alma (lot 2), source de vérité versionnée.
-- Déjà appliqué en base. Registre : première personne familière pour Alma,
-- vouvoiement absolu pour la personne, deux phrases maximum, aucun emoji,
-- aucun tiret cadratin, aucun superlatif.
INSERT INTO public.alma_moods (mood, content, weather_condition, season, time_of_day, weight) VALUES
('petillante', 'Le soleil tape sur votre région aujourd''hui. J''ai déjà fait trois fois le tour du jardin.', 'clair', NULL, 'matin', 2),
('petillante', 'Journée sèche chez vous. C''est le genre de jour où on ramène de la boue quand même.', 'clair', NULL, 'matin', 2),
('petillante', 'Ciel dégagé sur votre coin. J''ai réveillé tout le monde à six heures, personne ne m''a remerciée.', 'clair', NULL, 'matin', 1),
('petillante', 'Beau temps chez vous ce matin. Je suis prête à sortir depuis quarante minutes.', 'clair', NULL, 'matin', 1),
('petillante', 'Le soleil est là. J''ai mis la laisse dans la gueule, le message est passé.', 'clair', NULL, NULL, 1),
('petillante', 'Grand ciel bleu sur votre région. J''ai couru après mon ombre, elle court vite.', 'clair', NULL, NULL, 1),
('petillante', 'Matinée lumineuse chez vous. J''ai décidé que la journée serait bonne, à huit heures pile.', 'clair', 'printemps', 'matin', 1),
('pelotonnee', 'Il pleut chez vous. Je me suis installée près du radiateur et je bouge plus.', 'pluie', NULL, NULL, 2),
('pelotonnee', 'Le vent souffle sur votre coin. Mes oreilles ont doublé de volume.', 'vent', NULL, NULL, 2),
('pelotonnee', 'La pluie tombe depuis ce matin chez vous. J''ai renoncé au jardin, avec dignité.', 'pluie', NULL, NULL, 1),
('pelotonnee', 'Il fait froid sur votre région. Je me suis roulée en boule, format compact.', 'froid', NULL, NULL, 2),
('pelotonnee', 'Temps humide chez vous. Je regarde la porte, la porte reste fermée, on est d''accord.', 'pluie', NULL, NULL, 1),
('pelotonnee', 'Le froid s''installe sur votre coin. J''ai pris le coin du canapé, celui près de la fenêtre.', 'froid', 'hiver', NULL, 1),
('pelotonnee', 'Rafales sur votre région aujourd''hui. Chaque feuille qui passe me demande un avis.', 'vent', NULL, NULL, 1),
('reveuse', 'La nuit tombe tôt maintenant. C''est l''heure où je regarde par la fenêtre sans raison.', NULL, 'automne', 'soir', 2),
('reveuse', 'Les feuilles tombent chez vous. J''en ai poursuivi une pendant vingt minutes, elle a gagné.', NULL, 'automne', NULL, 2),
('reveuse', 'La lumière baisse déjà. Je repense au facteur de ce matin, il avait l''air pressé.', NULL, 'hiver', 'soir', 1),
('reveuse', 'Fin de journée chez vous. Je fais le tour des pièces, une dernière fois, par principe.', NULL, NULL, 'soir', 1),
('reveuse', 'Le jardin sent l''humidité ce soir. Je reste sur le pas de la porte, à écouter.', NULL, 'automne', 'soir', 1),
('reveuse', 'Les journées raccourcissent. J''ai pris l''habitude de m''endormir à la lumière du salon.', NULL, 'hiver', 'soir', 1),
('reveuse', 'Le soir arrive doucement. J''aime bien cette heure, tout le monde ralentit en même temps.', NULL, NULL, 'soir', 1),
('chiffonnee', 'Je retrouve plus l''os que j''avais enterré. Je crois que quelqu''un a tondu.', NULL, NULL, NULL, 2),
('chiffonnee', 'Toujours pas sortie en forêt aujourd''hui. Je compte les heures.', NULL, NULL, NULL, 2),
('chiffonnee', 'Ma balle est sous le canapé. Le canapé a gagné.', NULL, NULL, NULL, 2),
('chiffonnee', 'J''ai aboyé sur le facteur. Il n''a rien compris, moi non plus.', NULL, NULL, NULL, 2),
('chiffonnee', 'On m''a lavée ce matin. Je sens la pomme, ce n''était pas mon choix.', NULL, NULL, NULL, 1),
('chiffonnee', 'Le chat du jardin d''à côté me fixe depuis une heure. Je tiens bon.', NULL, NULL, NULL, 1),
('chiffonnee', 'Mon panier a été déplacé de trente centimètres. Je réapprends tout.', NULL, NULL, NULL, 1),
('attentive', 'Votre garde commence demain. Je reste concentrée.', NULL, NULL, NULL, 2),
('attentive', 'Une candidature attend votre réponse. Je garde le fil, dites-moi si vous voulez la relire.', NULL, NULL, NULL, 2),
('attentive', 'Votre départ approche. Je regarde ce qui reste à caler, à votre rythme.', NULL, NULL, NULL, 1),
('attentive', 'Il y a du mouvement sur votre dossier aujourd''hui. Je vous suis.', NULL, NULL, NULL, 1),
('attentive', 'Votre garde démarre bientôt. Je reste à côté, au cas où.', NULL, NULL, NULL, 1),
('attentive', 'Une réponse est attendue de votre côté. Je vous laisse la main.', NULL, NULL, NULL, 1),
('endormie', 'Il est tard chez vous. Je dors déjà, à moitié.', NULL, NULL, 'nuit', 2),
('endormie', 'La maison est calme. Je garde un oeil ouvert, le strict minimum.', NULL, NULL, 'nuit', 2),
('endormie', 'Nuit tranquille sur votre coin. Je reprends demain matin.', NULL, NULL, 'nuit', 2),
('endormie', 'Tout le monde dort ici. Je fais pareil, je vous retrouve plus tard.', NULL, NULL, 'nuit', 1),
('endormie', 'Il fait nuit chez vous. Je me suis installée au pied du lit.', NULL, NULL, 'nuit', 1),
('endormie', 'La journée est finie. Je range mes idées et je m''allonge.', NULL, NULL, 'nuit', 1);
