ALTER TABLE articles ADD COLUMN IF NOT EXISTS hero_image_alt TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS internal_links JSONB DEFAULT '[]'::jsonb;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();